@startuml
'https://plantuml.com/sequence-diagram

autonumber

sqs -> lambda: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml